config/routes.rb
Rails.application.routes.draw do

  resources :gams_paths
  resources :event_job_job_associations
  resources :event_job_period_associations
  resources :periods
  resources :jobs
  resources :events

  resources :users
  resources :microposts,          only: [:create, :destroy]

  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'

  get 'home'       => 'static_pages#home'
  get 'support'    => 'static_pages#support'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'signup'     => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post 'event_job_periods/delete_old_plan', :to => 'event_job_period_associations#delete_old_plan'
  post 'event_job_periods/optimize', :to => 'event_job_period_associations#optimize'
  post 'event_job_periods/read_optimization_results', :to => 'event_job_period_associations#read_optimization_results'

  post "periods/change", as: :change_periods

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :jobs, dependent: :destroy
  has_many :event_job_period_associations, dependent: :destroy
  has_many :event_job_job_associations, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :eventtext, :guest, :deadline)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :eventtext %><br>
    <%= f.text_field :eventtext %>
  </div>
  <div class="field">
    <%= f.label :guest %><br>
    <%= f.number_field :guest %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table id="events" class="display">
  <thead>
  <tr>
    <th>Anlass</th>
    <th>Kurze Beschreibung und Wünsche</th>
    <th>Anzahl der Gäste</th>
    <th>Deadline</th>
    <th></th>
    <th></th>
    <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.eventtext %></td>
        <td><%= event.guest %></td>
        <td><%= event.deadline %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>
<br>  <br><%= link_to 'Zurück zur Eventplanung', tcpsp_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Eventtext:</strong>
  <%= @event.eventtext %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @event.guest %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @event.deadline %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>